# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_endorsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsed', to=settings.AUTH_USER_MODEL)),
                ('user_endorsing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='skillset',
            name='endorsements',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='user_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
