# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20171222_2240'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
